# Generated by Django 5.2 on 2025-06-06 18:49

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_alter_projectversion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فصل')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='projects.project')),
            ],
            options={
                'verbose_name': 'فصل پروژه',
                'verbose_name_plural': 'فصول پروژه',
                'ordering': ['order'],
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام جدول')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='projects.projectchapter')),
            ],
            options={
                'verbose_name': 'جدول پویا',
                'verbose_name_plural': 'جداول پویا',
                'ordering': ['order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ستون')),
                ('column_type', models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('calculated', 'محاسباتی'), ('reference', 'ارجاع')], max_length=20, verbose_name='نوع ستون')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='فرمول محاسبه')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.dynamictable')),
            ],
            options={
                'verbose_name': 'ستون جدول',
                'verbose_name_plural': 'ستون\u200cهای جدول',
                'ordering': ['order'],
                'unique_together': {('table', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CalculationFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فرمول')),
                ('scope', models.CharField(choices=[('cell', 'سلول'), ('row', 'ردیف'), ('column', 'ستون'), ('table', 'جدول'), ('chapter', 'فصل'), ('cross_chapter', 'بین فصول')], max_length=20, verbose_name='قلمرو')),
                ('formula', models.TextField(verbose_name='فرمول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('source_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_formulas', to='projects.dynamictable')),
                ('target_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_formulas', to='projects.dynamictable')),
                ('source_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_formulas', to='projects.tablecolumn')),
                ('target_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_formulas', to='projects.tablecolumn')),
            ],
            options={
                'verbose_name': 'فرمول محاسباتی',
                'verbose_name_plural': 'فرمول\u200cهای محاسباتی',
            },
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('label', models.CharField(max_length=200, verbose_name='برچسب ردیف')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='projects.dynamictable')),
            ],
            options={
                'verbose_name': 'ردیف جدول',
                'verbose_name_plural': 'ردیف\u200cهای جدول',
                'ordering': ['order'],
                'unique_together': {('table', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CalculationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=200, verbose_name='کلید کش')),
                ('cached_value', models.JSONField(verbose_name='مقدار کش شده')),
                ('last_updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_cache', to='projects.project')),
            ],
            options={
                'verbose_name': 'کش محاسبات',
                'verbose_name_plural': 'کش محاسبات',
                'unique_together': {('project', 'cache_key')},
            },
        ),
        migrations.CreateModel(
            name='CellValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('calculated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='مقدار محاسبه شده')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='projects.tablecolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='projects.tablerow')),
            ],
            options={
                'verbose_name': 'مقدار سلول',
                'verbose_name_plural': 'مقادیر سلول\u200cها',
                'unique_together': {('row', 'column')},
            },
        ),
    ]
