# Generated by Django 5.1.3 on 2025-06-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialfield',
            name='field_type',
            field=models.CharField(choices=[('numeric', 'عدد'), ('text', 'متن')], max_length=50, verbose_name='نوع فیلد'),
        ),
        migrations.AlterField(
            model_name='financialfield',
            name='financial_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='categories.financialtable', verbose_name='جدول مالی'),
        ),
        migrations.AlterField(
            model_name='financialfield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='financialfield',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.unit', verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='financialtable',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_tables', to='categories.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='financialtable',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='financialtable',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
