# Generated by Django 5.2 on 2025-06-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_financialfield_field_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialfield',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='financialfield',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
