# Generated by Django 5.2 on 2025-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_financialfield_options_financialfield_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtable',
            name='section',
            field=models.CharField(choices=[('capex', 'سرمایه\u200cگذاری ثابت'), ('opex', 'هزینه\u200cهای متغیر'), ('revenue', 'درآمد/فروش'), ('analysis', 'تحلیل و شاخص\u200cها')], default='capex', max_length=20, verbose_name='فصل'),
        ),
    ]
