# Generated by Django 5.1.3 on 2025-06-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_financialtable_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtable',
            name='table_type',
            field=models.CharField(choices=[('grid', 'جدولی'), ('text', 'متنی'), ('auto', 'خودکار')], default='grid', max_length=10, verbose_name='نوع جدول'),
        ),
    ]
