# Generated by Django 5.1.3 on 2025-06-06 08:14

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_alter_financialfield_field_type_and_more'),
        ('projects', '0003_alter_project_options_alter_projectversion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_data', models.JSONField(verbose_name='داده عکس\u200cفوری')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_snapshots', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'عکس\u200cفوری مالی',
                'verbose_name_plural': 'عکس\u200cفوری\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='داده جدول')),
                ('computed_metrics', models.JSONField(blank=True, null=True, verbose_name='شاخص\u200cهای محاسبه\u200cشده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('financial_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_data', to='categories.financialtable', verbose_name='جدول مالی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'داده مالی پروژه',
                'verbose_name_plural': 'داده\u200cهای مالی پروژه',
                'unique_together': {('project', 'financial_table')},
            },
        ),
    ]
