# Generated by Django 5.2 on 2025-06-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_financialtable_table_type'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('row', 'سطح ردیف'), ('table', 'سطح جدول'), ('section', 'سطح فصل'), ('project', 'کل طرح')], default='table', max_length=20, verbose_name='سطح')),
                ('result_key', models.CharField(max_length=100, verbose_name='کلید نتیجه')),
                ('expression', models.TextField(verbose_name='عبارت فرمول')),
                ('financial_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='categories.financialtable', verbose_name='جدول مالی')),
            ],
            options={
                'verbose_name': 'فرمول مالی',
                'verbose_name_plural': 'فرمول\u200cهای مالی',
                'unique_together': {('financial_table', 'result_key', 'level')},
            },
        ),
    ]
