# Generated by Django 5.1.3 on 2024-12-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_alter_projectversion_options_and_more'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projects.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='similar_projects',
            field=models.ManyToManyField(related_name='recommended_for', to='projects.project', verbose_name='پروژه\u200cهای مشابه'),
        ),
    ]
