# Generated by Django 5.1.3 on 2024-12-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'پیشنهاد', 'verbose_name_plural': 'پیشنهادات'},
        ),
    ]
