# Generated by Django 5.1.3 on 2024-12-22 18:33

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_unit_options_and_more'),
        ('energy_fuel_prices', '0002_alter_energyfueltype_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricesetting',
            options={'verbose_name': 'تنظیم قیمت', 'verbose_name_plural': 'تنظیمات قیمت'},
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='business_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_settings', to='categories.category', verbose_name='نوع کسب\u200cوکار'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='energy_fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_settings', to='energy_fuel_prices.energyfueltype', verbose_name='نوع سوخت و انرژی'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_settings', to='energy_fuel_prices.region', verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='season',
            field=models.CharField(choices=[('spring', 'بهار'), ('summer', 'تابستان'), ('autumn', 'پاییز'), ('winter', 'زمستان')], max_length=50, verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
