# Generated by Django 5.1.3 on 2024-12-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_unit_options_and_more'),
        ('expenses', '0002_initial'),
        ('projects', '0003_alter_project_options_alter_projectversion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'هزینه', 'verbose_name_plural': 'هزینه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'دسته\u200cبندی هزینه', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای هزینه'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.unit', verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
